// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v3.21.12
// source: scraper.proto

package scraperpb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	NewsScraper_GetTopNews_FullMethodName = "/main.NewsScraper/GetTopNews"
)

// NewsScraperClient is the client API for NewsScraper service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type NewsScraperClient interface {
	GetTopNews(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*NewsResponse, error)
}

type newsScraperClient struct {
	cc grpc.ClientConnInterface
}

func NewNewsScraperClient(cc grpc.ClientConnInterface) NewsScraperClient {
	return &newsScraperClient{cc}
}

func (c *newsScraperClient) GetTopNews(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*NewsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(NewsResponse)
	err := c.cc.Invoke(ctx, NewsScraper_GetTopNews_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// NewsScraperServer is the server API for NewsScraper service.
// All implementations must embed UnimplementedNewsScraperServer
// for forward compatibility.
type NewsScraperServer interface {
	GetTopNews(context.Context, *Empty) (*NewsResponse, error)
	mustEmbedUnimplementedNewsScraperServer()
}

// UnimplementedNewsScraperServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedNewsScraperServer struct{}

func (UnimplementedNewsScraperServer) GetTopNews(context.Context, *Empty) (*NewsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetTopNews not implemented")
}
func (UnimplementedNewsScraperServer) mustEmbedUnimplementedNewsScraperServer() {}
func (UnimplementedNewsScraperServer) testEmbeddedByValue()                     {}

// UnsafeNewsScraperServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to NewsScraperServer will
// result in compilation errors.
type UnsafeNewsScraperServer interface {
	mustEmbedUnimplementedNewsScraperServer()
}

func RegisterNewsScraperServer(s grpc.ServiceRegistrar, srv NewsScraperServer) {
	// If the following call pancis, it indicates UnimplementedNewsScraperServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&NewsScraper_ServiceDesc, srv)
}

func _NewsScraper_GetTopNews_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NewsScraperServer).GetTopNews(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NewsScraper_GetTopNews_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NewsScraperServer).GetTopNews(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

// NewsScraper_ServiceDesc is the grpc.ServiceDesc for NewsScraper service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var NewsScraper_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "main.NewsScraper",
	HandlerType: (*NewsScraperServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetTopNews",
			Handler:    _NewsScraper_GetTopNews_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "scraper.proto",
}
